security:
    encoders:
        '%app.access.user_class%':
            id: App\Access\Security\Symfony\PasswordEncoder
            
    role_hierarchy: {}

    providers:
        custom:
            id: App\Access\Security\Symfony\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true


    access_control: {}
