security:
    encoders:
        '%app.access.user_class%':
            algorithm: bcrypt
            cost: 12
            
    role_hierarchy: {}

    providers:
        custom:
            id: App\Access\Security\User\Provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true


    access_control: {}
