parameters:
    'app.access.user_class': 'App\Access\Document\User'
    'app.access.user_contacts_class': 'App\Access\Document\UserContacts'
    'app.access.user_settings_class': 'App\Access\Document\UserSettings'

services:
    App\Access\Factory\UserIdentityFactoryInterface: '@App\Access\Factory\UserIdentity\UserIdentityEmailFactory'
    App\Access\Factory\UserAuthenticityFactoryInterface: '@App\Access\Factory\UserAuthenticity\UserAuthenticityPasswordFactory'
    App\Access\Security\AccessControlInterface: '@App\Access\Security\AccessControl'
    App\Access\Factory\UserFactoryInterface: '@App\Access\Factory\UserFactory'    

doctrine_mongodb:
    document_managers:
        default:
            mappings:
                Access: 
                    dir: '%kernel.project_dir%/src/Access/Document'
                    prefix: App\Access\Document
                    type: 'annotation'
                    is_bundle: false
                
twig:
    paths:
        '%kernel.project_dir%/src/Access/templates': 'Access'